os: windows

language: rust

rust:
  - stable
  - beta
jobs:
  fast_finish: true
  
cache: cargo
deploy:
  provider: releases
  file_glob: true
  overwrite: true
  file: target/release/server.zip
  skip_cleanup: true
  on:
    all_branches: true
    tags: false
    repo: Tiltmouse/Tiltmouse-server-retranslator
  api_key:
    secure: $UPLOAD_KEY
