os:
  - linux
  - osx
  - windows

language: rust

rust:
  - stable
  - beta
jobs:
  fast_finish: true

script: cargo build --verbose --release;
  
cache: cargo

before_deploy:
  - "if [[ -f target/release/server ]]; then mv target/release/server-release \"target/release/server-$TRAVIS_TAG-$TRAVIS_OS_NAME\"; fi"

deploy:
  provider: releases
  overwrite: true
  file:
    - target/release/server-*
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_RUST_VERSION = stable"
    branch: master
  api_key:
    secure: $UPLOAD_KEY
